import {createFileRoute} from '@tanstack/react-router'
import {useEffect,useRef,useState} from 'react'
import {ArrowDown,ArrowLeft,ArrowRight,ArrowUp,ArrowUpRight,Check,ChevronDown,Command,Download,Eye,Hand,Home,Keyboard,LockKeyhole,LogOut,MousePointer2,Play,Settings2,ShieldCheck,Smartphone,Square,Terminal,Wifi,X} from 'lucide-react'
import s from '../workspace.module.css'
export const Route=createFileRoute('/')({ssr:false,component:Workspace})
type Action={type:string;x?:number;y?:number;end_x?:number;end_y?:number;text?:string;key?:string;duration?:number}
type Cal={left:number;right:number;top:number;bottom:number;rotation:number}
type State={device:{connected:boolean;video:boolean;hid:boolean;control:boolean;detail:string;frame_at:number;width:number;height:number};run:null|{id:string;task:string;status:string;step:number;pending:null|{action:Action;reason:string}};events:{id:number;at:number;kind:string;text:string}[];calibration:Cal;model:string}
async function api(path:string,data?:unknown,method?:string){const r=await fetch('/api/'+path,{method:method||(data===undefined?'GET':'POST'),headers:data===undefined?{}:{'Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)});const body=await r.json();if(!r.ok)throw new Error(typeof body.detail==='string'?body.detail:r.status===422?'Check the input values.':`Request failed (${r.status})`);return body}
function Workspace(){
 const [authed,setAuthed]=useState<boolean|null>(null),[code,setCode]=useState(''),[data,setData]=useState<State|null>(null),[error,setError]=useState(''),[task,setTask]=useState(''),[text,setText]=useState(''),[busy,setBusy]=useState(false),[approve,setApprove]=useState(true),[tab,setTab]=useState<'activity'|'controls'>('activity'),[settings,setSettings]=useState(false),[cal,setCal]=useState<Cal>({left:0,right:0,top:0,bottom:0,rotation:0}),[frame,setFrame]=useState(''),[frameError,setFrameError]=useState(false)
 const pointer=useRef<{x:number;y:number;t:number}|null>(null),lastFrame=useRef(0),url=useRef(''),log=useRef<HTMLDivElement>(null)
 const refresh=async()=>{const d=await api('state');setData(d);return d as State}
 useEffect(()=>{const boot=async()=>{try{const token=location.hash.slice(1);if(token){history.replaceState(null,'',location.pathname);await api('session',{token})}await refresh();setError('');setAuthed(true)}catch{setAuthed(false)}};boot();window.addEventListener('hashchange',boot);return()=>window.removeEventListener('hashchange',boot)},[])
 useEffect(()=>{if(!authed)return;let live=true,timeout:ReturnType<typeof setTimeout>;async function poll(){try{const d=await api('state') as State;if(!live)return;setData(d);setError(e=>e==='Connection interrupted. Retrying…'?'':e);if(d.device.video && d.device.frame_at!==lastFrame.current){const r=await fetch('/api/frame');if(r.ok){const blob=await r.blob();if(!live)return;const next=URL.createObjectURL(blob);if(url.current)URL.revokeObjectURL(url.current);url.current=next;setFrame(next);setFrameError(false);lastFrame.current=d.device.frame_at}}}catch{if(live){setError('Connection interrupted. Retrying…');setData(old=>old?{...old,device:{...old.device,connected:false,video:false,hid:false}}:old)}}finally{if(live)timeout=setTimeout(poll,650)}}poll();return()=>{live=false;clearTimeout(timeout)}},[authed])
 useEffect(()=>{log.current?.scrollTo({top:log.current.scrollHeight,behavior:'smooth'})},[data?.events.length])
 const perform=async(fn:()=>Promise<unknown>)=>{setBusy(true);setError('');try{await fn();await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const active=!!data?.run && ['running','approval'].includes(data.run.status),ready=!!data?.device.video&&!!data?.device.hid&&!!data?.device.control,screenReady=!!data?.device.video&&!!frame&&!frameError
 const action=(a:Action)=>perform(()=>api('action',a))
 const swipe=(direction:string)=>{const ends:Record<string,[number,number]>={up:[.5,.25],down:[.5,.75],left:[.2,.5],right:[.8,.5]};action({type:'swipe',x:.5,y:.5,end_x:ends[direction][0],end_y:ends[direction][1],duration:.5})}
 const coords=(e:React.PointerEvent<HTMLImageElement>)=>{const r=e.currentTarget.getBoundingClientRect();return{x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))}}
 const unlock=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{await api('session',{token:code});setCode('');await refresh();setAuthed(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(authed===null)return <div className={s.loading}><div className={s.mark}><Hand size={25}/></div>Opening Glasshand…</div>
 if(!authed)return <div className={s.login}><div className={s.loginBox}><div className={s.brand}><span className={s.mark}><Hand size={23}/></span>glasshand<span className={s.wordTag}>WORKSPACE</span></div><div className={s.lock}><LockKeyhole size={27}/></div><h1>Connect to your phone.</h1><p>Enter your workspace access code to view the live screen and control the device.</p><form onSubmit={unlock}><label htmlFor="code">Access code</label><input id="code" type="password" value={code} onChange={e=>setCode(e.target.value)} autoComplete="current-password" autoFocus required/><button className={s.primary} disabled={busy}>{busy?'Connecting…':'Open workspace'}<ArrowUpRight size={18}/></button></form>{error&&<p role="alert" className={s.error}>{error}</p>}<div className={s.loginFoot}><ShieldCheck size={15}/>Private access · Hosted on Vultr</div></div></div>
 return <div className={s.app}>
 <header className={s.header}><a href="/" className={s.brand}><span className={s.mark}><Hand size={23}/></span>glasshand</a><div className={s.breadcrumb}>Workspace <span>/</span> iPhone 01</div><div className={s.headerRight}><span className={s.secure}><ShieldCheck size={14}/>Private session</span><a href="https://github.com/tkeith/glasshand" target="_blank" rel="noreferrer" className={s.repo}>Source<ArrowUpRight size={14}/></a><button className={s.iconButton} aria-label="Sign out" onClick={async()=>{setError('');try{await api('session',undefined,'DELETE');setAuthed(false);setData(null);setFrame('')}catch(e){setError((e as Error).message)}}}><LogOut size={17}/></button></div></header>
 <main className={s.main}><div className={s.titleRow}><div><div className={s.eyebrow}>DEVICE WORKSPACE</div><h1>iPhone 01 <span className={s.pill}><span className={data?.device.connected?s.greenDot:s.grayDot}/>{data?.device.connected?'Bridge online':'Bridge offline'}</span></h1><p>Observe the screen. Take control. Give your agent a task.</p></div><button className={s.stop} onClick={()=>perform(()=>api('stop',{}))}><Square size={14} fill="currentColor"/>Stop & take over</button></div>
 {error&&<div role="alert" className={s.alert}><span>{error}</span><button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
 <div className={s.workspace}>
 <section className={s.devicePanel} aria-label="Phone screen"><div className={s.panelHeader}><div><Smartphone size={17}/><strong>Live view</strong><span className={s.muted}>Real iPhone</span></div><button className={s.iconButton} aria-label="Screen calibration" onClick={()=>{setCal(data?.calibration||cal);setSettings(!settings)}}><Settings2 size={17}/></button></div>
 <div className={s.screenStage}><div className={s.stageTop}><span><span className={screenReady?s.greenDot:s.amberDot}/>{screenReady?'LIVE CAPTURE':'AWAITING SIGNAL'}</span><span>HDMI → Pi → Vultr</span></div>
 {screenReady?<div className={s.imageContainer}><img alt="Live iPhone screen — click to tap, drag to swipe" src={frame} draggable={false} onError={()=>setFrameError(true)} onPointerDown={e=>{if(!ready||busy)return;pointer.current={...coords(e),t:Date.now()};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerUp={e=>{const start=pointer.current;pointer.current=null;if(!start||!ready||busy)return;const end=coords(e);if(Math.hypot(end.x-start.x,end.y-start.y)>.035)action({type:'swipe',x:start.x,y:start.y,end_x:end.x,end_y:end.y,duration:Math.min(2,Math.max(.1,(Date.now()-start.t)/1000))});else action({type:'tap',x:end.x,y:end.y})}} onPointerCancel={()=>{pointer.current=null}}/></div>:<div className={s.phoneOutline}><div className={s.notch}/><div className={s.noSignal}><div className={s.signalIcon}><Smartphone size={30}/></div><h2>{data?.device.connected?'Waiting for video':'Connecting to device'}</h2><p>{data?.device.connected?'Unlock the iPhone and check the HDMI connection. The screen will appear here automatically.':'The Raspberry Pi bridge will reconnect automatically when it is online.'}</p><span className={s.waiting}><span className={s.amberDot}/>{data?.device.connected?'No HDMI signal':'Bridge offline'}</span></div><div className={s.homeBar}/></div>}
 <div className={s.stageBottom}><MousePointer2 size={14}/>{ready?'Click to tap · Drag to swipe':screenReady&&!data?.device.control?'Read-only · Phone is in use by another operator':'Controls become available when video and USB are connected'}</div></div>
 {settings&&<div className={s.calibration}><div><strong>Screen calibration</strong><button aria-label="Close calibration" className={s.iconButton} onClick={()=>setSettings(false)}><X size={16}/></button></div><p>Crop black borders so the image matches the phone display. Calibrate before using pointer input.</p><div className={s.calGrid}>{(['left','right','top','bottom'] as const).map(k=><label key={k}>{k} %<input type="number" min="0" max="95" value={cal[k]} onChange={e=>setCal({...cal,[k]:Number(e.target.value)})}/></label>)}<label>Rotation<select value={cal.rotation} onChange={e=>setCal({...cal,rotation:Number(e.target.value)})}>{[0,90,180,270].map(v=><option key={v} value={v}>{v}°</option>)}</select></label></div><button className={s.secondary} disabled={busy||active} onClick={()=>perform(async()=>{await api('calibration',cal);setSettings(false)})}>Apply calibration</button></div>}
 <div className={s.deviceFooter}><span><span className={data?.device.video?s.greenDot:s.amberDot}/>Video {data?.device.video?'live':'no signal'}</span><span><span className={data?.device.hid?s.greenDot:s.amberDot}/>USB {data?.device.hid?'connected':'not attached'}</span><span className={s.transport}><Wifi size={13}/>NetBird</span></div></section>
 <aside className={s.side}>
 <section className={s.taskPanel}><div className={s.panelHeader}><div><Command size={17}/><strong>Agent task</strong></div><span className={s.mode}>VISION + ACTION</span></div><div className={s.taskBody}><label htmlFor="task">What should the phone do?</label><textarea id="task" placeholder="Open Settings and check the battery percentage…" value={task} onChange={e=>setTask(e.target.value)} maxLength={2500} rows={4}/><div className={s.taskOptions}><label><input type="checkbox" checked={approve} onChange={e=>setApprove(e.target.checked)}/>Approve each action</label><span>20-step limit</span></div>{!approve&&<p className={s.autoNote}>The agent can tap and type automatically. Sensitive actions still request approval.</p>}<button className={s.primary} disabled={!ready||busy||active||task.trim().length<3} onClick={()=>perform(()=>api('run',{task:task.trim(),approve_each:approve}))}><Play size={15} fill="currentColor"/>{active?'Task in progress':'Run task'}<span>↵</span></button>{!ready&&<p className={s.help}>{data?.device.connected&&!data.device.control?'Read-only while another operator uses the phone.':'Waiting for live video and USB control.'}</p>}{data?.run&&<div className={s.runStatus}><span className={active?s.greenDot:s.grayDot}/><strong>{({running:'Working',approval:'Waiting for approval',completed:'Completed',stopped:'Stopped',error:'Needs attention',needs_input:'Needs your input'} as Record<string,string>)[data.run.status]}</strong><span>Step {data.run.step} / 20</span></div>}
 {data?.run?.pending&&<div className={s.approval}><div><ShieldCheck size={17}/><strong>Review next action</strong></div><p>{data.run.pending.reason}</p><code>{JSON.stringify(data.run.pending.action)}</code><div><button className={s.secondary} disabled={busy} onClick={()=>perform(()=>api('decision',{approve:false}))}>Decline</button><button className={s.primary} disabled={busy} onClick={()=>perform(()=>api('decision',{approve:true}))}><Check size={15}/>Approve</button></div></div>}</div></section>
 <section className={s.activityPanel}><div className={s.tabs}><button className={tab==='activity'?s.selected:''} onClick={()=>setTab('activity')}><Terminal size={15}/>Activity<span>{data?.events.length||0}</span></button><button className={tab==='controls'?s.selected:''} onClick={()=>setTab('controls')}><Keyboard size={16}/>Manual control</button></div>
 {tab==='activity'?<><div className={s.activity} ref={log}>{!data?.events.length?<div className={s.empty}><Eye size={23}/><strong>Every action, in view.</strong><p>Task observations and device acknowledgements will appear here.</p></div>:data.events.map(e=><div key={e.id} className={s.event}><span className={[s.eventIcon,['error','stop'].includes(e.kind)?s.eventError:''].join(' ')}>{e.kind==='manual'?<MousePointer2 size={13}/>:e.kind==='complete'?<Check size={13}/>:['error','stop'].includes(e.kind)?<Square size={11}/>:e.kind==='device'?<Wifi size={13}/>:<Command size={13}/>}</span><div><div className={s.eventMeta}><strong>{e.kind}</strong><time>{new Date(e.at*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</time></div><p>{e.text}</p></div></div>)}</div><div className={s.logFooter}><span>Device acknowledgements, not assumptions</span><a href="/api/history" aria-label="Download action log"><Download size={15}/></a></div></>:<div className={s.controls}><div className={s.controlTitle}><Hand size={17}/><span>Manual input takes over from the agent.</span></div><div className={s.keys}><button disabled={!ready||busy} onClick={()=>action({type:'key',key:'home'})}><Home size={16}/>Home</button><button disabled={!ready||busy} onClick={()=>action({type:'key',key:'enter'})}>↵ Enter</button><button disabled={!ready||busy} onClick={()=>action({type:'key',key:'backspace'})}>⌫ Delete</button></div><label htmlFor="type">Type on the phone</label><textarea id="type" rows={3} value={text} onChange={e=>setText(e.target.value)} placeholder="Text for the focused field" maxLength={500}/><div className={s.typeRow}><span>US English keyboard</span><button className={s.secondary} disabled={!ready||busy||!text} onClick={()=>perform(async()=>{await api('action',{type:'type',text});setText('')})}><Keyboard size={15}/>Send text</button></div><div className={s.swipes}><span>Swipe</span>{([['left',ArrowLeft],['up',ArrowUp],['down',ArrowDown],['right',ArrowRight]] as const).map(([dir,Icon])=><button key={dir} aria-label={'Swipe '+dir} disabled={!ready||busy} onClick={()=>swipe(dir)}><Icon size={17}/></button>)}</div></div>}
 </section><div className={s.sideFoot}><span className={s.greenDot}/>Orchestrated on Vultr <span>·</span> Real device execution</div>
 </aside></div><footer className={s.footer}><span>GLASSHAND <span>/</span> AGENT ARENA 2026</span><span>Vultr Cloud Compute · NetBird</span></footer></main></div>
}
